cmake_minimum_required(VERSION 3.21)
# if(CMAKE_ARGC LESS 5)
#     message(FATAL_ERROR "Usage: cmake -P create_md5sum.cmake <file_to_hash> <target_file>")
# endif()
# set(FILE_TO_HASH ${CMAKE_ARGV3})
# set(TARGET_FILE ${CMAKE_ARGV4})
if(NOT FILE_TO_HASH OR NOT TARGET_FILE)
    message(FATAL_ERROR "Usage: cmake –DFILE_TO_HASH=<intput_file> -DTARGET_FILE=<target file> -P CreateSha256.cmake")
endif()
file(MD5SUM "${FILE_TO_HASH}" GENERATED_HASH)
file(WRITE "${TARGET_FILE}" "${GENERATED_HASH}")